# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherDataProxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire' 

  # Pods for WeatherDataProxy

  target 'WeatherDataProxyTests' do
    # Pods for testing
  end

end
